# Generated by Django 5.2.8 on 2025-11-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthdate",
            field=models.DateField(
                blank=True, help_text="Укажите дату рождения", null=True, verbose_name="Дата рождения"
            ),
        ),
    ]
